### ISSUE TITLE
scrollbar styles

### ISSUE THREAD

**Issue by Twintails** [atom/styleguide#21]
Hi I'm looking to see if there is any info on styling the scrollbars?

I'm not certain what the elements are in the Atom panes and would like to eliminate the white from the nice dark theme I use :-)

it would be cool to do this, 
.pane-scrollbar .tree-view-scrollbar {
 background-color: darken(@tree-view-background-color, 2%); //or call the parent element color n'such
 .thumb . button {
     color: lighten(@tree-view-background-color, 2%);
  }
}

here is a post on webkit scrollbars. just wondering if there is some documentation on Atom scrollbars
http://css-tricks.com/custom-scrollbars-in-webkit/

Thanks!

**Comment by lee-dohm** [comment]
There is this topic on Discuss that talks about styling the scrollbars:

https://discuss.atom.io/t/ugly-scrollbars-bug/1027

Hope that helps!

**Comment by Twintails** [comment]
It did! Many thanks!
