### ISSUE TITLE
Links to external Octicons page refers to wrong version

### ISSUE THREAD

**Issue by lee-dohm** [atom/styleguide#33]
Related to #31 

<img width="536" alt="napkin 12-30-15 2 14 47 pm" src="https://cloud.githubusercontent.com/assets/1038121/12058317/af34e67c-aeff-11e5-979c-1e5f0328cbd5.png">

I'm not sure if there is a page you can point to that shows old versions of the Octicons, but I feel like this might create some confusion for designers and package authors.

/cc @simurai

**Comment by simurai** [comment]
We could replace that line with something like:

> See the icons section to get an overview of all Octicons.

**Comment by lee-dohm** [comment]
Yeah, I think that would be good.
