### ISSUE TITLE
Styleguide for radio buttons is invalid

### ISSUE THREAD

**Issue by zmb3** [atom/styleguide#54]
The examples for radio buttons and checkboxes aren't valid HTML:

`<label class='input-label'><input class='input-radio' type='radio' name='radio'> Radio</label>`

Note that the `input` element is never closed.

I think it should read:

`<label class='input-label'><input class='input-radio' type='radio' name='radio' /> Radio</label>`

**Comment by 50Wliu** [comment]
From MDN:
> Must have a start tag and must not have an end tag.

In addition, none of the MDN examples include a self-closing tag.  Therefore, I'm closing this as invalid and wontfix.

**Comment by zmb3** [comment]
Good to know.  I guess the issue I ran into is that `<input>` _does_ need a closing tag in JSX :-)
