### ISSUE TITLE
Add Atomicons to Icons Section of StyleGuide

### ISSUE THREAD

**Issue by liuderchi** [atom/styleguide#62]
Currently Style Guide Shows only Octicons.

It would be great if we can show Atomicons, which are used in Outline-View in [Atom-ide](https://ide.atom.io/).

Atomicons are available at https://github.com/atom/atom/blob/master/static/variables/octicon-utf-codes.less#L4-L21.

**Comment by simurai** [comment]
I was hoping to keep the Atomicons "private" for now and officially introduce them as SVG icons. Not sure how soon that will happen though.

If you want to use them in a package, feel free. But they might get replaced sooner or later.
