### ISSUE TITLE
Selected text hidden in some lists

### ISSUE THREAD

**Issue by sasquatch666** [atom/styleguide#67]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

The selected portions of the list in the basic list view, and the lists with "disclosure arrows at only one level", is completely hidden by the selection. This occurs in all combos of ui/syntax themes I have tried.
<img width="706" alt="screen shot 2018-04-11 at 10 57 12 am" src="https://user-images.githubusercontent.com/1795161/38634912-b1535c68-3d78-11e8-9d8f-bba30f8820c8.png">
<img width="748" alt="screen shot 2018-04-11 at 11 02 52 am" src="https://user-images.githubusercontent.com/1795161/38634935-c4de1688-3d78-11e8-8f2c-0e462df5d59f.png">
The selections appear as they should in the other list views.
<img width="591" alt="screen shot 2018-04-11 at 11 00 22 am" src="https://user-images.githubusercontent.com/1795161/38634960-db66f7da-3d78-11e8-8b59-256b0a548b15.png">

<img width="677" alt="screen shot 2018-04-11 at 11 00 49 am" src="https://user-images.githubusercontent.com/1795161/38634974-e3a13d98-3d78-11e8-9e94-fae88516dc05.png">

I have reproduced this in safe mode, using Atom Light/Atom Dark/One Light/One Dark UI themes, in combination with various syntax themes.

**Comment by simurai** [comment]
I think the problem is that Atom relies that there is a child element:

https://github.com/atom/atom-ui/blob/05f2c50993148594f8350a410fbac6d0f2385f15/styles/lists.less#L222-L225

That's why the "With icons" works. I'll make PR that adds `<span>`s like:

```html
<li class='list-item'><span>Normal item</span></li>
```

@sasquatch666 Thanks for reporting.
